server:
  port: 8001
  servlet:
    context-path: /auth
spring:
  jackson:
    time-zone: GMT+8
  application:
    name: ams-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: industry_user
    password: OFwcmF~dw0lz
    url: jdbc:mysql://192.168.169.235:3306/ams?serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      one:
        max-active: 100 #最大连接数
        min-idle: 20 #最小连接数
        max-wait: 2000 #超时时间（ms）
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    cluster:
      nodes: 192.168.169.92:7001,192.168.169.93:7002,192.168.169.94:7003,192.168.169.95:7004,192.168.169.96:7005,192.168.169.97:7006
    password: zr%k23idS5q9
    #   nodes: 192.168.202.138:7051,192.168.202.139:7052,192.168.202.140:7053,192.168.202.141:7054,192.168.202.142:7055,192.168.202.143:7056
    # password: nmoL!FlFmmY5
mybatis-plus:
  # configuration:
  #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #   map-underscore-to-camel-case: true
  type-aliases-package: com.mysteel.ams.entity
  mapper-locations: classpath:*/*Mapper.xml
logging:
  level:
    com.mysteel.ams.mapper: debug
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

